on: [push]

name: AzureLoginSample

jobs:

  whitelist-ip:
    runs-on: ubuntu-latest

    steps:
    - name: Get runner IP
      run: echo "::set-output name=runner_ip::$(curl ifconfig.io)"
      id: runner_ip

    - name: Whitelist runner IP on Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        script: |
          az network nsg rule create --name SSH --nsg-name <nsg-name> --priority 100 --source-address-prefixes ${{ steps.runner_ip.outputs.runner_ip }}/32 --destination-port-ranges 22 --protocol Tcp

    - name: SSH into VM and run commands
      uses: appleboy/ssh-action@master
      with:
        host: <vm-public-ip>
        username: <username>
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          ls
          whoami
          df
