on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Whitelist GitHub Runner IP
        uses: azure/CLI@v1
        with:
          inlineScript: |
            set -eu
            agentIP=$(curl -s https://api.ipify.org/)
            az network nic ip-config update \
            --name ipconfig1 \
            --nic-name demo-nps \
            --resource-group demo azure \
            --public-ip-address $agentIP
            sleep 300

